// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase configuration. These must be provided
// in the deployment environment (e.g. Vercel) without any fallbacks.
// The bang operator (!) asserts that these variables are defined.
const supabaseUrl: string = process.env.SUPABASE_URL!;
const supabaseKey: string = process.env.SUPABASE_ANON_KEY!;

// Export a single Supabase client instance using the provided URL and key.
export const supabase = createClient<Database>(supabaseUrl, supabaseKey);