// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/*
 * In the original project the Supabase URL and anonymous key were
 * hard‑coded into this client. To support different environments and
 * avoid accidentally committing secrets to the repository the values
 * should come from environment variables instead.  The user asked to
 * standardise on SUPABASE_URL and SUPABASE_ANON_KEY.  These variables
 * must be defined at build time (for example in a .env file or the
 * deployment environment).  Falling back to undefined will cause the
 * client constructor to throw if they are missing.
 */
const SUPABASE_URL: string | undefined = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY: string | undefined = process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  // In development you can set these variables in a .env file.  At runtime
  // the app will throw immediately if they are missing so the developer
  // notices the misconfiguration.
  throw new Error('Supabase environment variables SUPABASE_URL and SUPABASE_ANON_KEY must be provided');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});